SET SERVEROUTPUT ON;

--------------------------------------------------------
-- Scenario 1
-- Update Customer LastModified
--------------------------------------------------------

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

--------------------------------------------------------
-- Test
--------------------------------------------------------

UPDATE Customers
SET Balance = Balance + 1000
WHERE CustomerID = 1;

COMMIT;

--------------------------------------------------------
-- Scenario 2
-- Audit Log Trigger
--------------------------------------------------------

CREATE TABLE AuditLog(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog(
        TransactionID,
        AccountID,
        Amount,
        TransactionDate
    )

    VALUES(

        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        SYSDATE

    );

END;
/

--------------------------------------------------------
-- Test
--------------------------------------------------------

INSERT INTO Transactions
VALUES(
10,
1,
SYSDATE,
500,
'Deposit'
);

COMMIT;

--------------------------------------------------------
-- Scenario 3
-- Check Transaction Rules
--------------------------------------------------------

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW

DECLARE

    v_balance NUMBER;

BEGIN

    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID=:NEW.AccountID;

    IF :NEW.TransactionType='Withdrawal'
    AND :NEW.Amount>v_balance THEN

        RAISE_APPLICATION_ERROR(
        -20010,
        'Insufficient Balance');

    END IF;

    IF :NEW.TransactionType='Deposit'
    AND :NEW.Amount<=0 THEN

        RAISE_APPLICATION_ERROR(
        -20011,
        'Deposit Amount Must Be Positive');

    END IF;

END;
/

--------------------------------------------------------
-- Test
--------------------------------------------------------

INSERT INTO Transactions
VALUES(
20,
1,
SYSDATE,
200,
'Deposit'
);

COMMIT;